### PR TITLE
chore: pin flutter version in GitHub Actions

### PR DESCRIPTION
**Pull request by bernardobelchior**
Pins the flutter version to v3 and upgrades `graphic` to Flutter 3.

### CODE REVIEW

**Comment by entronad** [comment]
Is it necessary to force people use flutter 2?
The limits of flutter I set in the pubspec.yaml is '>=2.6.0', no upper limit. In fact I have recently upgrade my flutter to 3.0.0, there seems no breaking changes involving Graphic.
I think in the next months, there will be both a lot developers using 2 and 3.

**Comment by entronad** [comment]
I would prefer pinning the tests to Flutter 3.

**Comment by bernardobelchior** [comment]
Done, @entronad! Upgraded to Flutter 3 and pinned that version 😄

**Comment by entronad** [comment]
Published in v0.10.4
Since the nullablility of RendererBinding.instance is different in 2 and 3, I removed the mouse checking, which is not necessary.

**Pull request merged**
