### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Asimbaloch**
Thanks for the readers is added

### CODE REVIEW

**Comment by jpackardts** [comment]
Why merge a spam PR

**Comment by V3ntus** [comment]
Merging a spam PR for hacktoberfest, nice

**Comment by entronad** [comment]
What dose "hacktoberfest" mean?

**Comment by V3ntus** [comment]
It's a shitty annual coding festival where people come together to spam low effort PRs to every repo they can get their hands on all for a T-shirt and stickers.

**Comment by entronad** [comment]
Well, his is the first time I've heard of this festival.

I came across this PR while organizing issues, and although it didn't seem to have much value, I merged it to encourage contributors.

I didn't realize it was from this festival. But that's okay, this festival sounds very punk, and I quite like punk things.

**Pull request merged**
